name: sre_api_python
services:
  api_python:
    container_name: api_python
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"

name: sre_monitoring

services:
  prometheus:
    container_name: prometheus
    image: ubuntu/prometheus:3-24.04_stable
    volumes:
      - ../monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    volumes:
    - ./monitoring/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    command:
    - "--config.file=/etc/alertmanager/alertmanager.yml"
    ports:
    - "9093:9093"

  jenkins-agent:
    build:
      context: ..
      dockerfile: Dockers/files/Dockerfile
    container_name: jenkins-agent
    ports:
      - "2222:22"
    volumes:
           - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - sre_api_python_default

  datadog:
    image: datadog/agent:latest
    container_name: datadog
    environment:
    - DD_API_KEY=${DD_API_KEY}
    - DD_SITE=${DD_SITE}
    - DD_LOGS_ENABLED=true
    - DD_APM_ENABLED=true
    - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /proc:/host/proc:ro
    - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
    ports:
    - "8126:8126"  # APM
    - "8125:8125/udp"  # metrics

volumes:
  jenkins_home: