name: sre_monitoring
services:
  prometheus:
    container_name: prometheus
    image: ubuntu/prometheus:3-24.04_stable
    volumes:
      - ../monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
    - sre_api_python_default
  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
  datadog:
    image: datadog/agent:latest
    container_name: datadog
    environment:
    - DD_API_KEY=${DD_API_KEY}
    - DD_SITE=${DD_SITE}
    - DD_LOGS_ENABLED=true
    - DD_APM_ENABLED=true
    - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /proc:/host/proc:ro
    - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
    ports:
    - "8126:8126"  # APM
    - "8125:8125/udp"  # metrics
    networks:
    - sre_api_python_default

networks:
  sre_api_python_default:
    driver: bridge
    external: true