events {}

http {
    upstream app {
        server api_python:8000;

    }

    server {
        listen 80;

        location / {
            proxy_pass http://app;
        }

        location /health {
            proxy_pass http://app/health;
        }

        location /stub_status {
            stub_status;
        }
    }
}