pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh 'docker build -t sre-api .'
            }
        }
        stage('Test') {
            steps {
                sh 'pytest'
            }
        }
        stage('Deploy') {
            steps {
                sh 'docker-compose up -d'
            }
        }
    }
}